CREATE TABLE users (
    id SERIAL PRIMARY KEY,
    name VARCHAR(511) NOT NULL,
    email VARCHAR(511) NOT NULL,
    password VARCHAR(511) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP NOT NULL DEFAULT NOW(),
    deleted_at TIMESTAMP DEFAULT NULL
);

